### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by paskal** [apavlushina/MuseumApp-frontend#5]
Hello, thank you for the nice project! Would you be so kind as to provide a link to the demo site (if you have it deployed somewhere like Heroku) in the Readme? It would be really convenient to be able to use it without having to install node on the local machine.

**Comment by paskal** [comment]
Bump: I'm still very interested in seeing deployed version.

**Comment by apavlushina** [comment]
So am I) 
I have met some unexpected difficulties with deployment and didn't work on it during my holidays.
Now I am back and will try to do it again!

**Comment by apavlushina** [comment]
it works! http://nameless-peak-28155.herokuapp.com/map

**Comment by paskal** [comment]
I suggest to put it into description: 
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/712534/74376496-83f46100-4de2-11ea-8c8b-d0f4691bd18f.png">
